Weekly Exercise 1

In [1]:
Panjang = 20.5
Lebar = 25
Tinggi = 10

Keliling = 2 * (Panjang + Lebar)
Luas = Panjang * Lebar
Volume = Panjang * Lebar * Tinggi

print("Panjang=", Panjang)
print("Lebar=", Lebar)
print("Tinggi=", Tinggi)
print("Keliling=", Keliling)
print("Volume = ", Volume)

Panjang= 20.5
Lebar= 25
Tinggi= 10
Keliling= 91.0
Volume =  5125.0

Weekly Exercise 2

In [2]:
R_S = (85 + 75)/2
print('1. Rata-rata nilai Shafira pada kedua mata kuliah adalah', R_S)

JN_HA = (75 + 90 + 70 + 75)
print('2. Jumlah nilai Hanif dan Andi untuk semua mata kuliah adalah', JN_HA)

R_WDHN_K = (85+ 85 + 80 + 95)/4
R_WDHN_MS = (85 + 85 + 75 + 80)/4
print('3. Rata-rata nilai Widya, Dhanar, Hikma, dan Nedia pada mata kuliah Kalkulus 1 adalah', R_WDHN_K)
print('   Rata-rata nilai Widya, Dhanar, Hikma, dan Nedia pada mata kuliah Metode Statistika adalah', R_WDHN_MS)

R_K_SEMUA = (85 + 80 + 75 + 95 + 85 + 75 + 70 + 85 + 80)/9
print('4. Rata-rata nilai mata kuliah Kalkulus 1 semua mahasiswa adalah', R_K_SEMUA)

R_MS_SEMUA = (75 + 90 + 80 + 80 + 85 + 90 + 75 + 85 + 75)/9
print('5. Rata-rata nilai mata kuliah Metode Statistika semua mahasiswa adalah', R_MS_SEMUA)

1. Rata-rata nilai Shafira pada kedua mata kuliah adalah 80.0
2. Jumlah nilai Hanif dan Andi untuk semua mata kuliah adalah 310
3. Rata-rata nilai Widya, Dhanar, Hikma, dan Nedia pada mata kuliah Kalkulus 1 adalah 86.25
   Rata-rata nilai Widya, Dhanar, Hikma, dan Nedia pada mata kuliah Metode Statistika adalah 81.25
4. Rata-rata nilai mata kuliah Kalkulus 1 semua mahasiswa adalah 81.11111111111111
5. Rata-rata nilai mata kuliah Metode Statistika semua mahasiswa adalah 81.66666666666667

Weekly Exercise 3

In [4]:
G_A = 8 * 30000 * 31
G_Potongan = 8 * 30000 * 3
G_Dwi = G_A - G_Potongan
print('1. Gaji yang diterima Dwi padaa bulan Agustus adalah', G_Dwi)

T_Dwi = 10 * G_Dwi // 100
print('2. Tunjangan yang diterima Dwi pada bulan Agustus adalah', T_Dwi)

L_Dwi = 10000 * 5
G_Total = G_Dwi + T_Dwi + L_Dwi
print('3. Gaji total yang diterima Dwi pada nulan Agustus adalah', G_Total)

1. Gaji yang diterima Dwi padaa bulan Agustus adalah 6720000
2. Tunjangan yang diterima Dwi pada bulan Agustus adalah 672000
3. Gaji total yang diterima Dwi pada nulan Agustus adalah 7442000